### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by josiahdavis** [verdimrc/py-ds-template#4]
Getting an error when running this: `FileNotFoundError: [Errno 2] No such file or directory: 'src/josiahcctest'`

See here for the full traceback:

```bash
cookiecutter https://github.com/verdimrc/py-ds-template.git
You've downloaded /home/ec2-user/.cookiecutters/py-ds-template before. Is it okay to delete and re-download it? [yes]: yes
project_name [My new project]: josiahcctest
repo_name [my-repo]: josiahcctest
author_name [Your name (or your organization/company/team)]: josiahdavis
description [A short description of the project.]: blah
Select open_source_license:
1 - No license file
2 - MIT License
3 - Apache-2.0 License
Choose from 1, 2, 3 [1]: 3
Select python_interpreter:
1 - python3
2 - python
Choose from 1, 2 [1]: 1
package_name []: josiahcctest
Traceback (most recent call last):
  File "/tmp/tmp2mld1jr6.py", line 9, in <module>
    pkg_dir.mkdir()
  File "/home/ec2-user/anaconda3/lib/python3.7/pathlib.py", line 1268, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'src/josiahcctest'
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)
```

**Comment by verdimrc** [comment]
Thanks for noticing this. Just committed a fix 369f1ee.

Please try again and let me know.

**Comment by verdimrc** [comment]
Thanks for noticing this. Just committed a fix 369f1ee.

Please try again and let me know.

**Comment by josiahdavis** [comment]
Works like a charm :sparkles:

**Comment by yperms** [comment]
I'm making a small platform game as a complete beginner and I'm trying to load a background using:

#load images
bg_img = pygame.image.load('img/sky.png')

When I then try to run it, it tells me this:

 bg_img = pygame.image.load('img/sky.png')
FileNotFoundError: No such file or directory.

What do I have to do? The picture (sky.png) is in a folder named "img" in my files. Do I have to somehow upload it to pygame before I run that code or will it find it in my files on my computer?
