### ISSUE TITLE
File not found problem

### ISSUE THREAD

**Issue by yperms** [verdimrc/py-ds-template#5]
I'm making a small platform game as a complete beginner and I'm trying to load a background using:

#load images
bg_img = pygame.image.load('img/sky.png')

When I then try to run it, it tells me this:

 bg_img = pygame.image.load('img/sky.png')
FileNotFoundError: No such file or directory.

What do I have to do? The picture (sky.png) is in a folder named "img" in my files. Do I have to somehow upload it to pygame before I run that code or will it find it in my files on my computer?

**Comment by verdimrc** [comment]
hi, I am not familiar with pygame. Perhaps it's best that you open an issue on Pygame github repo.

Thanks,
Verdi

**Comment by yperms** [comment]
alright, thanks anyways
